export const GET_PICTURES_REQUESTED = "GET_PICTURES_REQUESTED"
export const GET_PICTURES_SUCCESS = "GET_PICTURES_SUCCESS"
export const GET_PICTURES_FAIL = "GET_PICTURES_FAIL"

export const POST_PICTURES_REQUESTED = "POST_PICTURES_REQUESTED"
export const POST_PICTURES_SUCCESS = "POST_PICTURES_SUCCESS"
export const POST_PICTURES_FAILED = "POST_PICTURES_FAILED"

export const DELETE_PICTURES_REQUESTED = "DELETE_PICTURES_REQUESTED"
export const DELETE_PICTURES_SUCCESS = "DELETE_PICTURES_SUCCESS"
export const DELETE_PICTURES_FAILED = "DELETE_PICTURES_FAILED"

export const EDIT_PICTURES_REQUESTED = "EDIT_PICTURES_REQUESTED"
export const EDIT_PICTURES_SUCCESS = "EDIT_PICTURES_SUCCESS"
export const EDIT_PICTURES_FAILED = "EDIT_PICTURES_FAILED"